config/routes.rb
As2::Application.routes.draw do
  devise_for :users

  root 'projects#index'
  resources :projects do 
    resources :members, only: [:index,:update,:new,:create]
    resources :tasks do
      resources :assignees, only: [:index,:update,:new,:create]
    end
    resources :discussions do
      resources :comments
    end
  end

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :comments, as: :commentable,dependent: :destroy
  has_many :commenters, through: :comments, source: :user
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :get_project
  before_action :get_discussion, only: [:show,:destroy,:edit,:update]

  def index
    # @owned=current_user.discussions
    @owned=@proj.discussions.where("user_id=?",current_user.id)   # current_user.projects.find(@proj).tasks.order("completed asc")
    @proj_discussions=@proj.discussions
  end

  def new
    @discussion=current_user.discussions.new
  end

  def create
    @discussion=current_user.discussions.new params.require(:discussion).permit([:title,:body])
    @discussion.project=@proj
    if @discussion.save
      redirect_to project_path(@proj)
    else
      render :new
    end
  end

  def destroy
    if (current_user.discussions.include? @discussion)
      @discussion.destroy
      redirect_to project_path(@proj)
    else
      redirect_to :back, alert: 'You do not own this discussion'
    end
  end

  def show
    @comments=@discussion.comments
    @comment=Comment.new
  end

  # def manage_collaborators
  #   @users=@proj.members
  #   render :collaborators_form
  # end

  # def add_remove_collaborators
  #   redirect_to root_path
  # end

  def edit
    @users=@proj.members
    @users.push(@proj.user) unless @proj.members.include? @proj.user
  end

  def update
    @discussion.update_attributes params.require(:discussion).permit([:title,:body,:user_id])
    if @proj.save
      redirect_to project_discussion_path(@proj,@discussion)
    else
      render :edit
    end
  end

  private

  # def get_disc_params
  #   params.require(:discussion).permit([:title,:body])
  # end


  def get_discussion
    # get_project
    id=params[:discussion_id] || params[:id]
    begin 
      @discussion=@proj.discussions.find(id)
    rescue  ActiveRecord::RecordNotFound
          # TODO: redirect to 404 or maybe 401
          # redirect_to root_path
          redirect_to root_path, alert: "Discussion #{id} does not exist or you do not have access to it."
    end
  end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_for [@proj,@discussion] do |f| %>
  <% if @discussion.errors.any? %>
    <ul>
      <% @discussion.errors.full_messages.each do |message| %>
      <li class='rederror'><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div><%= f.label :title, "Discussion title" %>
    <br>
    <%= f.text_field :title%>
  </div>
    <br>
  <div>
    <%= f.label :body, "Discussion text" %>
    <br>
    <%= f.text_area :body  %>
  </div>
  <% if @discussion.persisted? %>
  <h2>Change discussion's owner</h2>
  <div>
    <p>Note: If you change the owner, you will no longer be able to edit the discussion.</p>
    <% @users.each do |user| %>
    <%= radio_button_tag('discussion[user_id]',user.id,(@discussion.user==user),id: dom_id(user))%>
    <%= f.label "user's email", user.email,id: dom_id(user) %>
    <% end %>
  <% end %>
  <%= f.submit "Save" %>
<% end %>

app/views/discussions/collaborators_form.html.erb
<%= form_for [@proj,discu, url: :proj_collabs do |f| %>
  <ul>
  <% @users.each do |user| %>
  <%= f.label "user's email", user.email %>
  <%= check_box_tag('task[user_ids][]',user.id,@proj.members.include?(user) ) %>
  <% end %>
  </ul>
<%= f.submit 'submit' %>
<%end %> 

app/views/discussions/edit.html.erb
<%= render "form" %>

app/views/discussions/index.html.erb
	<%= content_for :title, "Discussions for you" %> 
	<!-- #{current_user.email} -->
<%= link_to "Create new discussion",new_project_discussion_path%>
	<h2>Discussions you own</h2>
    <ul>
    <% @owned.each do |owned| %>
      <li>Title: <%= link_to owned.title, project_discussion_path(@proj,owned) %>
        <ul>
        <li>Body: <%= truncate_s(owned.body,30) %></li>
        <li><%= button_to "Delete discussion",project_discussion_path(@proj,owned),method: :delete, data: {confirm: "Are you sure you want to delete this?"} %></li>
      </ul></li>
    <% end %>
    </ul>
  <h2>Discussions you are a member of</h2>
    <ul>
    <% @proj_discussions.each do |proj_discussion| %>
      <li>Title: <%= link_to proj_discussion.title, project_discussion_path(@proj,proj_discussion) %></li>
      <li>Body: <%= truncate_s(proj_discussion.body,30) %></li>
    <% end %>
    </ul>

app/views/discussions/new.html.erb
<%= render "form" %>

app/views/discussions/show.html.erb
<h2>Discussion <%=@discussion.id%> details</h2>
<dl>
  <dt>Discussion Name:</dt>
    <dd><%= @discussion.title %></dd>
  <dt>Description:</dt>
    <dd><%= @discussion.body %></dd>
<% if current_user.can_modify_discussion? @discussion %>
  <%= link_to("modify",edit_project_discussion_path(@proj,@discussion))%>
  <%= button_to("delete discussion",project_discussion_path(@proj,@discussion),method: :delete, data: {confirm: "Are you sure you want to delete this?"}) %>
<%end%>
<% if @comments[0] %>
<ul>
  <% @comments.each do |comment| %>
  <li>By <%= comment.user.email%> at <%=comment.created_at.to_formatted_s(:long)%>: &nbsp; &nbsp; &nbsp;
  <% if current_user.can_modify_comment? comment %>
    <%= link_to("modify",edit_project_discussion_comment_path(@proj,@discussion,comment))%>
    <%= button_to("delete comment",project_discussion_comment_path(@proj,@discussion,comment),method: :delete, data: {confirm: "Are you sure you want to delete this?"}) %>
  <%end%>
    <ul>
   <li><%= comment.body %></li></ul>
    </li>
  <% end%>
</ul>
<%end%>
<%= render "comment_form" %>
</dl>
<%= link_to "Back to discussions page for project #{@proj.id}", project_discussions_path(@proj) %>