config/routes.rb
As2::Application.routes.draw do
  devise_for :users

  root 'projects#index'
  resources :projects do 
    resources :members, only: [:index,:update,:new,:create]
    resources :tasks do
      resources :assignees, only: [:index,:update,:new,:create]
    end
    resources :discussions do
      resources :comments
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :task_assignees
  has_many :assignees, through: :task_assignees, source: :user
  validate :due_date_checker
  # has_many :task_assignees, through: :, source: 

  has_many :comments, as: :commentable,dependent: :destroy
  has_many :commenters, through: :comments, source: :user

  def due_date_checker
    if !due.present? || due < Date.today
      errors.add(:due, " date should be filled and should be in the future.")
    end
  end

  def complete?
    self.completed ? 'Completed' : 'In Progress'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_project
  before_action :get_task, only: [:show,:destroy,:edit,:update]
  before_action :authorize, only: [:destroy,:update]
  def index
    @owned=@proj.tasks.where("user_id=?",current_user.id).order("completed")  # current_user.projects.find(@proj).tasks.order("completed asc")
    @assigned=current_user.assigned_tasks.where("project_id=?",@proj.id).order("completed")
    # current_user.projects.find(@proj).tasks.order("completed asc")
  end

  def new
    @task=current_user.tasks.new
  end

  def create
    @task=current_user.tasks.new params.require(:task).permit([:name,:description,:due])
    @task.project=@proj
    @task.assignees << current_user if params[:task][:assignee]=='yes'
    if @task.save
      redirect_to project_path(@proj)
    else
      render :new
    end
  end

  def destroy
    if (current_user.tasks.include? @task)
      @task.destroy
      redirect_to :back, notice: 'Task removed.'
    else
      redirect_to project_tasks_path @proj, alert: 'You do not own this task'
    end
  end

  def show
  end

  # def manage_collaborators
  #   @users=@proj.members
  #   render :collaborators_form
  # end

  # def add_remove_collaborators
  #   redirect_to root_path
  # end

  def edit
    @users=@proj.members
    @users.push(@proj.user) unless @proj.members.include? @proj.user
  end

  def update
    @task.update_attributes params.require(:task).permit([:name,:description,:due,:completed,:user_id])
    if @proj.save
      redirect_to project_task_path(@proj,@task)
    else
      render :edit
    end
  end

  private

  def get_task
    id=params[:task_id] || params[:id]
    begin 
      @task=@proj.tasks.find(id) if (@proj.user==current_user)
    rescue  ActiveRecord::RecordNotFound
      begin 
        @task=current_user.tasks.find(id)
      rescue ActiveRecord::RecordNotFound
        begin 
          @task=current_user.assigned_tasks.find(id)
        rescue ActiveRecord::RecordNotFound
          # TODO: redirect to 404 or maybe 401
          # redirect_to root_path
          redirect_to root_path, alert: "Task #{id} does not exist or you do not have access to it."
        end
      end
    end
  end

  def authorize
    redirect_to root_path,alert: "cannot" unless can? :manage,@task
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_change_status.html.erb
<% if current_user.can_finish_task? @task %>
  <%= form_for [@proj,@task] do |f|%>
    <% if @task.completed %>
      <%= hidden_field_tag 'task[completed]',"false"%>
      <%=f.submit "Mark as Incomplete" %>
    <% else %>
      <%= hidden_field_tag 'task[completed]',"true"%>
      <%=f.submit "Mark as Complete" %>
    <%end %>
  <% end %>
<%end %>

app/views/tasks/_form.html.erb
<%= form_for [@proj, @task] do |f| %>
  <% if @task.errors.any? %>
    <ul>
      <% @task.errors.full_messages.each do |message| %>
      <li class='rederror'><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div><%= f.label :name, "Task name" %>
    <br>
    <%= f.text_field :name %>
  </div>
    <br>
  <div>
    <%= f.label :description, "Task description" %>
    <br>
    <%= f.text_area :description  %>
  </div>
  <div>
    <%= f.label :due, "Task due date" %>
    <br>
    <%= f.date_field :due  %>
  </div>
  <br>
  <% if !@task.persisted? %>
  <div>
    <%= check_box_tag('task[assignee]',"yes", checked: "checked")%>
    <br>
    <%= f.label :description, "Add me to the task as an assignee." %>
  </div>
  <br>
  <% else %>
   <div>
    <%= f.label :completed, "Completed?" %>
    <br>
    <%= hidden_field_tag 'task[completed]',"false"%>
    <%= check_box_tag('task[completed]',"true",(@task.completed) ) %>
  </div>
  <h2>Change task's owner</h2>
  <div>
    <p>Note: If you change the owner, you will no longer be able to edit the task.</p>
    <% @users.each do |user| %>
    <%= radio_button_tag('task[user_id]',user.id,(@task.user==user),id: dom_id(user))%>
    <%= f.label "user's email", user.email,id: dom_id(user) %>
    <% end %>
  <% end %>
  <%= f.submit "Save" %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
	<%= content_for :title, "Tasks for YOU" %> 
	<!-- #{current_user.email} -->
<%= link_to "Create new task",new_project_task_path %>
	<table>
    <tr>
      <th colspan='2'>Project <%=@proj.id%> tasks you manage</th>
    </tr>
    <tr>
      <th>Task</th>
      <th>Progress</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
    <% @owned.each do |own| %>
    <tr>  
      <td><%= link_to own.name,project_task_path(@proj,own) %></td>
      <td><%= own.complete? %></td>
      <% @task=own %>
      <td><%= link_to("modify",edit_project_task_path(@proj,own))%></td>
      <td><%= render "change_status" %></td>
      <td><%= button_to("Delete task",project_task_path(@proj,own),method: :delete, data: {confirm: "Are you sure you want to delete this?"}) %></td>

    </tr>
    <% end %>
  </table>
  <br>
  <table>
    <tr>
      <th colspan='2'>Project <%=@proj.id%> tasks assigned to you</th>
    </tr>
    <tr>
      <th>Task</th>
      <th>Progress</th>
      <th>&nbsp;</th>
    </tr>
    <% @assigned.each do |assigned| %>
    <tr>  
      <td><%= link_to assigned.name,project_task_path(@proj,assigned) %></td>
      <td><%= assigned.complete? %></td>
      <% @task=assigned %>
      <td><%= render "change_status" %></td>
    </tr>
    <% end %>
  </table>
<%= link_to "Back to project #{@proj.id}",project_path(@proj) %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h2>Task <%=@task.id%> details</h2>
<dl>
  <dt>Task Name:</dt>
    <dd><%= @task.name %></dd>
  <dt>Description:</dt>
    <dd><%= @task.description %></dd>
  <dt>Due Date:</dt>
    <dd><%= @task.due %></dd>
  <dt>Status:</dt>
    <dd><%= @task.complete? %></dd>
  <dt>Assignees:</dt>
<% @task.assignees.each do |assignee| %>
    <dd><%= assignee.email %></dd>
<% end %>
<% if can? :edit, @task %>
  <%= link_to "Add or remove assignees",project_task_assignees_path(@proj,@task) %>
  <%= link_to("modify",edit_project_task_path(@proj,@task))%>
  <%= button_to("Delete task",project_task_path(@proj,@task),method: :delete, data: {confirm: "Are you sure you want to delete this?"}) %>
<%end%>
<%= render "change_status" %>
</dl>
<%= link_to "Back to tasks page for project #{@proj.id}", project_tasks_path(@proj) %>