config/routes.rb
As2::Application.routes.draw do
  devise_for :users

  root 'projects#index'
  resources :projects do 
    resources :members, only: [:index,:update,:new,:create]
    resources :tasks do
      resources :assignees, only: [:index,:update,:new,:create]
    end
    resources :discussions do
      resources :comments
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates_presence_of :title
  validates_presence_of :description

  belongs_to :user
  has_many :tasks,dependent: :destroy

  has_many :project_assignees
  has_many :members,through: :project_assignees, source: :user
  has_many :discussions
  after_save :propogate_removed_users
  has_many :comments, as: :commentable,dependent: :destroy
  has_many :commenters, through: :comments, source: :user

  def propogate_removed_users
    # assignee_ids=[]
    # tasks.each do |task|
    #   assignee_ids+=task.task_assignees.pluck([:id])
    # end
    TaskAssignee.where(["task_id in (?)", tasks.pluck(:id)]).
                where(["task_assignees.user_id NOT IN (?)", members.pluck(:id)]).
                destroy_all
    # p assignee_ids
    #   task.task_assignees.each do |assignee|
    #     if !members.include? assignee
    #        assignee.destroy
    #     end
    #   end
    # end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_project,only: [:show,:destroy,:edit,:update,:redirect_if_not_owner]#except: [:index,:new,:destroy]
  #,only: [:show,:destroy,:manage_collaborators]
  before_action :redirect_if_not_owner, only: [:destroy,:edit,:update]
  
  def index
    # @owned_projs=current_user.projects
    @member_projs=current_user.assigned_projects
    @owned_projs=Project.page(params[:page]).per_page(2)
  end

  def new
    @proj=current_user.projects.new
  end

  def create
    @proj=current_user.projects.new params.require(:project).permit([:title,:description])
    @proj.user=current_user
    @proj.members << current_user if params[:project][:collab]=='yes'
    if @proj.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @users=User.all
  end

  def update
    @proj.update_attributes params.require(:project).permit([:title,:description,:user_id])
    if @proj.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @tasks=@proj.tasks.order("completed asc")
    @discussions=@proj.discussions
  end

  def destroy
    id=@proj.id
    @proj.destroy
    redirect_to root_path, notice: "Project #{id} was removed."
  end

  private

  def redirect_if_not_owner
    if !current_user.can_modify_proj? get_project
      redirect_to root_path, alert: "You do not own project #{@proj.id}" 
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
  <% @users||=users %>
  <div class="modal-header">
    <p>Shite</p>
  </div>
<%= form_for @proj do |f| %>
  <% if @proj.errors.any? %>
    <ul>
      <% @proj.errors.full_messages.each do |message| %>
      <li class='rederror'><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div><%= f.label :title, "Project's title" %>
    <br>
    <%= f.text_field :title%>
  </div>
    <br>
  <div>
    <%= f.label :description, "Project's description" %>
    <br>
    <%= f.text_area :description  %>
  </div>
  <% if !@proj.persisted? %>
  <div>
    <%= check_box_tag('project[collab]',"yes", checked: "checked")%>
    <br>
    <%= f.label :description, "Add me to the project's collaboratos." %>
  </div>
  <br>
  <% else %>
  <h2>Change project's owner</h2>
  <div>
    <p>Note: If you change the owner, you will no longer be able to edit the project and might completely lose access to it if you are not on the collaborator's list.</p>
    <% @users.each do |user| %>
    <%= radio_button_tag('project[user_id]',user.id,(@proj.user==user),id: dom_id(user))%>
    <%= f.label "user's email", user.email,id: dom_id(user) %>
    <% end %>
  <% end %>
  <%= f.submit "Save" %>
</div>
<% end %>
  <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
</div>
</div>
</div>
</div>

app/views/projects/edit.html.erb
<%= render "form" %>

app/views/projects/index.html.erb
	<%= content_for :title, "Projects for YOU" %> 
	<!-- #{current_user.email} -->
<%= link_to "Create new project",new_project_path%>
	<h2>Projects you own</h2>
    <ul>
    <% @owned_projs.each do |owned| %>
      <li>Title: <%= link_to owned.title, project_path(owned) %>
        <ul>
        <li>Description: <%= truncate_s(owned.description,30) %></li>
        <li><%= link_to "Add or remove members",project_members_path(owned) %></li>
        <li><%= button_to "Delete project",project_path(owned),method: :delete, data: {confirm: "Are you sure you want to delete this?"} %></li>
      </ul></li>
    <% end %>
    </ul>
    <%= will_paginate @owned_projs, previous_label: "(prev)", next_label: "(next)" %>
  <h2>Projects you are a member of</h2>
    <ul>
    <% @member_projs.each do |member_in| %>
      <li>Title: <%= link_to member_in.title, project_path(member_in) %></li>
      <li>Description: <%= truncate_s(member_in.description,30) %></li>
    <% end %>
    </ul>

app/views/projects/new.html.erb
<%= render "form" %>

app/views/projects/show.html.erb
<%= link_to "Your tasks",project_tasks_path(@proj)%>
<%= link_to "Your projects",projects_path%>
<br>
<h3>Project <%=@proj.id%>'s tasks and discussions</h3>
 <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>
<%= render "form", users: @proj.members %>
<%= link_to "Create new task",new_project_task_path(@proj) %>
<% if @tasks[0] %>
  <table>
    <tr>
      <th>Task Name:</th>
      <th>Description:</th>
      <th>Due Date:</th>
      <th>Status:</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>  
  <% @tasks.each do |task| %>
    <tr>
      <td><%= link_to task.name,project_task_path(project_id: params[:id],id: task) %></td>
      <td><%= truncate_s(task.description,30) %></td>
      <td><%= task.due %></td>
      <td><%= task.complete? %></td>
      <td><%= current_user.can_modify_task?(task)? link_to("modify",edit_project_task_path(@proj,task)) : " "%></td>
      <td><%= current_user.can_modify_task?(task)? button_to("Delete task",project_task_path(@proj,task),method: :delete, data: {confirm: "Are you sure you want to delete this?"}) : " " %></td>
    </tr>
<% end %>
</table>
<% end %>
<br>
<br>
<br>
<br>
<%= link_to "Create new discussion",new_project_discussion_path(@proj) %>
<% if @discussions[0] %>
<table>
  <tr>
    <th>Discussion Title:</th>
    <th>Body:</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr> 
<% @discussions.each do |discussion| %>
  <tr>
    <td><%= link_to discussion.title,project_discussion_path(@proj,discussion) %></td>
    <td> <%= discussion.body %></td>
    <td><%= current_user.can_modify_discussion?(discussion)? link_to("modify",edit_project_discussion_path(@proj,discussion)) : " " %></td>
    <td><%= current_user.can_modify_discussion?(discussion)? button_to("Delete discussion",project_discussion_path(@proj,discussion),method: :delete, data: {confirm: "Are you sure you want to delete this?"}) : " " %></td>
  </tr>
</table>
<% end %>
<% end %>